// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Seat struct {
	ID     int32   `json:"id"`
	Status string  `json:"status"`
	UserID *string `json:"userId,omitempty"`
}

type Subscription struct {
}
