package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"graphql-service/graph/model"
	"ticket-system/shared/logger"
)

// LockSeat is the resolver for the lockSeat field.
func (r *mutationResolver) LockSeat(ctx context.Context, seatID int32, userID string) (*string, error) {
	if err := r.Client.Lock(int(seatID), userID); err != nil {
		return nil, err
	}

	msg := "locked"
	return &msg, nil
}

// ConfirmSeat is the resolver for the confirmSeat field.
func (r *mutationResolver) ConfirmSeat(ctx context.Context, seatID int32, userID string) (*string, error) {
	if err := r.Client.Pay(int(seatID), userID); err != nil {
		return nil, err
	}

	msg := "booked"
	return &msg, nil
}

// Seats is the resolver for the seats field.
func (r *queryResolver) Seats(ctx context.Context) ([]*model.Seat, error) {
	res, err := r.Client.GetSeats()
	if err != nil {
		return nil, err
	}

	var seats []*model.Seat

	for _, s := range res.Seats {

		var userID *string
		if s.UserId != "" {
			userID = &s.UserId
		}

		seats = append(seats, &model.Seat{
			ID:     s.Id,
			Status: s.Status,
			UserID: userID,
		})
	}

	return seats, nil
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context) ([]string, error) {
	return logger.GetLogs(), nil
}

// SeatUpdates is the resolver for the seatUpdates field.
func (r *subscriptionResolver) SeatUpdates(ctx context.Context) (<-chan *model.Seat, error) {
	id, ch := r.AddSubscriber()
	go func() {
		<-ctx.Done()
		r.RemoveSubscriber(id)
	}()
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
