// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ticket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{0}
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_proto_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *Seat) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Seat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SeatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*Seat                `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatList) Reset() {
	*x = SeatList{}
	mi := &file_proto_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatList) ProtoMessage() {}

func (x *SeatList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatList.ProtoReflect.Descriptor instead.
func (*SeatList) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *SeatList) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int32                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_proto_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *LockRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *LockRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int32                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatRequest) Reset() {
	*x = SeatRequest{}
	mi := &file_proto_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatRequest) ProtoMessage() {}

func (x *SeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatRequest.ProtoReflect.Descriptor instead.
func (*SeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *SeatRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type SeatConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int32                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatConfirmRequest) Reset() {
	*x = SeatConfirmRequest{}
	mi := &file_proto_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatConfirmRequest) ProtoMessage() {}

func (x *SeatConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatConfirmRequest.ProtoReflect.Descriptor instead.
func (*SeatConfirmRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *SeatConfirmRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *SeatConfirmRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int32                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_proto_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentRequest) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatResponse) Reset() {
	*x = SeatResponse{}
	mi := &file_proto_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatResponse) ProtoMessage() {}

func (x *SeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatResponse.ProtoReflect.Descriptor instead.
func (*SeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *SeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_ticket_proto protoreflect.FileDescriptor

const file_proto_ticket_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ticket.proto\x12\x06ticket\"\a\n" +
	"\x05Empty\"G\n" +
	"\x04Seat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\".\n" +
	"\bSeatList\x12\"\n" +
	"\x05seats\x18\x01 \x03(\v2\f.ticket.SeatR\x05seats\"?\n" +
	"\vLockRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x05R\x06seatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"&\n" +
	"\vSeatRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x05R\x06seatId\"F\n" +
	"\x12SeatConfirmRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x05R\x06seatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x0ePaymentRequest\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x05R\x06seatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"&\n" +
	"\fSeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9e\x02\n" +
	"\x10InventoryService\x12+\n" +
	"\bGetSeats\x12\r.ticket.Empty\x1a\x10.ticket.SeatList\x125\n" +
	"\bLockSeat\x12\x13.ticket.LockRequest\x1a\x14.ticket.SeatResponse\x127\n" +
	"\n" +
	"UnlockSeat\x12\x13.ticket.SeatRequest\x1a\x14.ticket.SeatResponse\x12?\n" +
	"\vConfirmSeat\x12\x1a.ticket.SeatConfirmRequest\x1a\x14.ticket.SeatResponse\x12,\n" +
	"\vSeatUpdates\x12\r.ticket.Empty\x1a\f.ticket.Seat0\x012~\n" +
	"\x0ePaymentService\x123\n" +
	"\x03Pay\x12\x16.ticket.PaymentRequest\x1a\x14.ticket.SeatResponse\x127\n" +
	"\n" +
	"StartTimer\x12\x13.ticket.SeatRequest\x1a\x14.ticket.SeatResponseB\x15Z\x13ticket-system/protob\x06proto3"

var (
	file_proto_ticket_proto_rawDescOnce sync.Once
	file_proto_ticket_proto_rawDescData []byte
)

func file_proto_ticket_proto_rawDescGZIP() []byte {
	file_proto_ticket_proto_rawDescOnce.Do(func() {
		file_proto_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ticket_proto_rawDesc), len(file_proto_ticket_proto_rawDesc)))
	})
	return file_proto_ticket_proto_rawDescData
}

var file_proto_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ticket_proto_goTypes = []any{
	(*Empty)(nil),              // 0: ticket.Empty
	(*Seat)(nil),               // 1: ticket.Seat
	(*SeatList)(nil),           // 2: ticket.SeatList
	(*LockRequest)(nil),        // 3: ticket.LockRequest
	(*SeatRequest)(nil),        // 4: ticket.SeatRequest
	(*SeatConfirmRequest)(nil), // 5: ticket.SeatConfirmRequest
	(*PaymentRequest)(nil),     // 6: ticket.PaymentRequest
	(*SeatResponse)(nil),       // 7: ticket.SeatResponse
}
var file_proto_ticket_proto_depIdxs = []int32{
	1, // 0: ticket.SeatList.seats:type_name -> ticket.Seat
	0, // 1: ticket.InventoryService.GetSeats:input_type -> ticket.Empty
	3, // 2: ticket.InventoryService.LockSeat:input_type -> ticket.LockRequest
	4, // 3: ticket.InventoryService.UnlockSeat:input_type -> ticket.SeatRequest
	5, // 4: ticket.InventoryService.ConfirmSeat:input_type -> ticket.SeatConfirmRequest
	0, // 5: ticket.InventoryService.SeatUpdates:input_type -> ticket.Empty
	6, // 6: ticket.PaymentService.Pay:input_type -> ticket.PaymentRequest
	4, // 7: ticket.PaymentService.StartTimer:input_type -> ticket.SeatRequest
	2, // 8: ticket.InventoryService.GetSeats:output_type -> ticket.SeatList
	7, // 9: ticket.InventoryService.LockSeat:output_type -> ticket.SeatResponse
	7, // 10: ticket.InventoryService.UnlockSeat:output_type -> ticket.SeatResponse
	7, // 11: ticket.InventoryService.ConfirmSeat:output_type -> ticket.SeatResponse
	1, // 12: ticket.InventoryService.SeatUpdates:output_type -> ticket.Seat
	7, // 13: ticket.PaymentService.Pay:output_type -> ticket.SeatResponse
	7, // 14: ticket.PaymentService.StartTimer:output_type -> ticket.SeatResponse
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ticket_proto_init() }
func file_proto_ticket_proto_init() {
	if File_proto_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ticket_proto_rawDesc), len(file_proto_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ticket_proto_goTypes,
		DependencyIndexes: file_proto_ticket_proto_depIdxs,
		MessageInfos:      file_proto_ticket_proto_msgTypes,
	}.Build()
	File_proto_ticket_proto = out.File
	file_proto_ticket_proto_goTypes = nil
	file_proto_ticket_proto_depIdxs = nil
}
